---
title: "OPEB analysis"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_notebook: 
    df_print: paged
    fig_height: 6
    fig_width: 8
    toc: yes
    number_sections: yes
editor_options:
  chunk_output_type: inline
---

```{r setup, eval=TRUE, include=FALSE, echo=FALSE, message=FALSE, warning=FALSE}

# note that eval=TRUE unless set to FALSE

knitr::opts_chunk$set(eval=TRUE, include=FALSE, echo=FALSE)
options(width = 150)
```

```{r libraries}
library(tidyverse)
options(tibble.print_max = 80, tibble.print_min = 80) # if more than nn rows, print 60 - enough for states
library(readxl)

library(btools)

# tables
library(knitr)
library(kableExtra)
library(DT)
library(gt)

library(maps)
# https://cran.r-project.org/web/packages/usmap/vignettes/mapping.html
library(usmap)
library(gridExtra)
library(RcppRoll)
library(ggrepel)
library(ggbreak)
library(patchwork)
library(RColorBrewer)

```

```{r constants}
dsacs <- r"(E:\data\CA_sacs/)"
dsacs_all <- paste0(dsacs, "data/allyears/")

dj90 <- r"(E:\data\CA_j90/)"
dj90_all <- paste0(dj90, "data/allyears/")

#.. graph theme items
legend_none <- theme(legend.position = "None")
legend_notitle <- theme(legend.title = element_blank())
caption_left <- theme(plot.caption = element_text(hjust = 0))


```

```{r logical_expressions}
sfusd <- expression(ccode==38 & dcode==68478)
```


# Marc Joffe's OPEB data

```{r joffe}
mjfn <- "OPEB Study Data 2021-02-18.xlsx"

mj1 <- read_excel(here::here("data", mjfn), sheet="OPEB Study Data")
# glimpse(mj1)
# summary(mj1)

mj2 <- mj1 %>%
  select(-...10) %>%
  rename(stabbr=state,
         penrev=`pension/revenue`,
         opebrev=`opeb/revenue`)
# summary(mj2)
# count(mj2, stabbr)

mjsd <- mj2 %>%
  filter(str_detect(name, coll("school", ignore_case = TRUE)))


```


<!-- ## Large California school districts in 2019: pensions and OPEB as % of revenue -->

```{r mj_largecasd, include=FALSE}
mjsd %>%
  filter(stabbr=="CA", total_revenues >= 100e6) %>%
  arrange(desc(opebrev)) %>%
  select(-c(year, opeb_liabilities_elsewhere)) %>%
  datatable(caption="California school districts in 2019 with total revenues >= $100m\n, Source: Marc Joffe",
            options=list(warn.size=FALSE,
                         pageLength = 25)) %>%
  formatCurrency(
    columns=c("pension_debt", "opeb_debt", "total_revenues"),
    currency = "",
    digits=0,
    interval = 3, 
    mark = ",") %>%
  formatPercentage(
    columns = c("penrev", "opebrev"),
    digits=1)
```

## Large California, Nevada, and Oregon school districts in 2019: pensions and OPEB as % of revenue
```{r mj_largesd, include=TRUE}
mjsd %>%
  filter(stabbr %in% c("CA", "NV", "OR"), total_revenues >= 100e6) %>%
  arrange(desc(opebrev)) %>%
  select(-c(year, opeb_liabilities_elsewhere)) %>%
  datatable(caption="California, Nevada, and Oregon school districts in 2019 with total revenues >= $100m. Source: Marc Joffe",
            options=list(warn.size=FALSE,
                         pageLength = 20)) %>%
  formatCurrency(
    columns=c("pension_debt", "opeb_debt", "total_revenues"),
    currency = "",
    digits=0,
    interval = 3, 
    mark = ",") %>%
  formatPercentage(
    columns = c("penrev", "opebrev"),
    digits=1)

```


# SACS financial data
```{r load_sacs}
system.time(all_sacs <- readRDS(paste0(dsacs_all, "all_sacs.rds")))
sacs_gfcurrent <- readRDS(file=paste0(dsacs_all, "sacs_gfcurrent.rds"))


```


## SFUSD Health, pension, and OPEB benefits as % of general fund
```{r shares, include=TRUE, fig.width=10, fig.height=6.5}
pdata <- sacs_gfcurrent %>%
  filter(eval(sfusd)) %>%
  select(year, current, gfopeb, ercpen, health) %>%
  mutate(currentadj=current + gfopeb) %>%  # opeb is not in current expenses
  pivot_longer(-c(year, current, currentadj)) %>%
  mutate(share=value / currentadj,
         name=factor(name,
                     levels=c("health", "ercpen", "gfopeb"),
                     labels=c("employee health", "pensions", "opeb"))) %>%
  arrange(name)

p <- pdata %>%
  ggplot(aes(year, share, color=name)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(name=NULL) +
  scale_y_continuous(name="% share", labels=percent, breaks=seq(0, 1, .025), limits = c(0, NA)) +
  labs(caption="Source: California Department of Education SACS financial data.") + 
  ggtitle("SFUSD health, pension, and OPEB cash expenditures as % of current education expense",
          subtitle="General fund only. Current expenses adjusted to include OPEB payments.") +
  theme_bw() +
  theme(plot.caption = element_text(hjust = 0, face="italic")) +
  legend_notitle
p

ggsave(plot=p, filename=here::here("results", "benefit_shares.png"), width=10, height=6.5, units="in")
write_csv(pdata, here::here("results", "benefit_shares_data.csv"))
    


```



## SFUSD OPEB nominal amounts
```{r include=FALSE}
df %>%
  filter(eval(sfusd)) %>%
  select(year, contains("opeb")) %>%
  pivot_longer(cols = -year) %>%
  ggplot(aes(year, value / 1e6, colour=name)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(name = "$ millions", breaks=seq(0, 100, 5), limits=c(0, NA)) +
  ggtitle("San Francisco GF OPEB benefit expenditures")
  
  
```

# SFUSD OPEB as % of total spending
```{r include=TRUE}
df %>%
  filter(eval(sfusd)) %>%
  mutate(opebpct=totopeb / (current + totopeb)) %>%
  ggplot(aes(year, opebpct)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(name = "% of spending", labels = scales::percent) +
  ggtitle("San Francisco GF OPEB benefit expenditures as % of total spending")
```


# Top OPEB-as-% of spending large districts
```{r include=TRUE}


```


# J-90 OPEB data
```{r}
opeb_j90 <- readRDS(paste0(dj90_all, "opeb.rds"))

```

```{r}
opeb_j90 %>%
  filter(eval(sfusd)) %>%
  filter(plantype=="health") %>%
  filter(year==2020) %>%
  mutate(erpct=totercost / sum(totercost),
         lbl=ifelse(erpct > .05, round(erpct, 2), "")) %>%
  ggplot(aes(x=planeecost, y=opebfte, size=erpct, colour=coverage, label=lbl)) +
  geom_point() +
  geom_text(nudge_x = 750, size=3) +
  scale_y_continuous("# of participants", labels = scales::comma) +
  scale_x_continuous("annual cost to the participant", labels=scales::comma) +
  ggtitle("SFUSD retired OPEB participants and per-retiree plan costs in 2020")
```

